sonar.projectKey=fullstack-demo
sonar.projectName=FullStack Demo
sonar.projectVersion=1.0

sonar.sources=backend,frontend
sonar.sourceEncoding=UTF-8

# 🔥 EXCLUDE virtual environments & dependencies
sonar.exclusions=**/venv/**,**/__pycache__/**,**/node_modules/**,**/dist/**,**/build/**

sonar.host.url=http://localhost:9000
