name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Setup Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t fastapi-app ./backend

      # 4️⃣ Tag Image for Nexus (DO NOT add http here)
      - name: Tag Image for Nexus
        run: |
          docker tag fastapi-app:latest \
          ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest

      # 5️⃣ Login to Nexus (IMPORTANT: use http://)
      - name: Login to Nexus
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login \
          http://${{ secrets.NEXUS_URL }} \
          --username ${{ secrets.NEXUS_USERNAME }} \
          --password-stdin

      # 6️⃣ Push Image to Nexus
      - name: Push Image to Nexus
        run: |
          docker push \
          ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest

      # 7️⃣ Deploy to EC2 Server
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            echo "Logging into Nexus on EC2..."
            echo "${{ secrets.NEXUS_PASSWORD }}" | docker login \
            http://${{ secrets.NEXUS_URL }} \
            --username ${{ secrets.NEXUS_USERNAME }} \
            --password-stdin

            echo "Pulling latest image..."
            docker pull ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest

            echo "Stopping old container..."
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            echo "Running new container..."
            docker run -d \
              --name fastapi-app \
              -p 8000:8000 \
              --restart always \
              ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest

            echo "Deployment Completed Successfully!"
