name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Setup Docker builder
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Docker Image (from backend folder)
      - name: Build Docker Image
        run: |
          docker build -t fastapi-app ./backend

      # 4️⃣ Tag image for Nexus
      - name: Tag Image for Nexus
        run: |
          docker tag fastapi-app:latest \
          ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest

      # 5️⃣ Login to Nexus (FORCE HTTP)
      - name: Login to Nexus
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login \
          http://${{ secrets.NEXUS_URL }} \
          --username ${{ secrets.NEXUS_USERNAME }} \
          --password-stdin

      # 6️⃣ Push image to Nexus
      - name: Push Image to Nexus
        run: |
          docker push \
          ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest

      # 7️⃣ Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login http://${{ secrets.NEXUS_URL }} \
              -u ${{ secrets.NEXUS_USERNAME }} \
              -p ${{ secrets.NEXUS_PASSWORD }}

            docker pull ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest

            docker stop fastapi-app || true
            docker rm fastapi-app || true

            docker run -d -p 8000:8000 \
              --name fastapi-app \
              ${{ secrets.NEXUS_URL }}/docker-hosted/fastapi-app:latest
